apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bol8pt59e-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bol8pt59e-nodejs 
  name: bol8pt59e-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bol8pt59e-nodejs 
